### ISSUE TITLE
Persistent Queue metrics are in a different place for Logstash 7.x

### ISSUE THREAD

**Issue by sparkblaze** [sequra/logstash_exporter#20]
I don't appear to be getting values for pipeline queue stats (we have several queues and a production load through them)

```
logstash_node_queue_events{pipeline="beats"} 0
# HELP logstash_node_queue_max_size_bytes queue_max_size_bytes
# TYPE logstash_node_queue_max_size_bytes counter
logstash_node_queue_max_size_bytes{pipeline="beats"} 0
# HELP logstash_node_queue_max_unread_events queue_max_unread_events
# TYPE logstash_node_queue_max_unread_events counter
logstash_node_queue_max_unread_events{pipeline="beats"} 0
# HELP logstash_node_queue_page_capacity_bytes queue_page_capacity_bytes
# TYPE logstash_node_queue_page_capacity_bytes counter
logstash_node_queue_page_capacity_bytes{pipeline="beats"} 0
# HELP logstash_node_queue_size_bytes queue_size_bytes
# TYPE logstash_node_queue_size_bytes counter
logstash_node_queue_size_bytes{pipeline="beats"} 0
```

From the Logstash API, it looks like these values are no longer nested under `pipelines.<pipeline>.queue.capacity` but are just under `pipelines.<pipeline>.queue`

```
{
  [...]
  "pipelines": {
    "beats": {
      [...]
      "queue": {
        "type": "persisted",
        "events_count": 0,
        "queue_size_in_bytes": 47788,
        "max_queue_size_in_bytes": 536870912
      }
``` 

Currently using Logstash 7.4.0 and Exporter 0.1.5.

**Comment by romarioschneider** [comment]
Make following change:
```
diff --git a/collector/nodestats_api.go b/collector/nodestats_api.go
index 4d7dbad..16f5bab 100644
--- a/collector/nodestats_api.go
+++ b/collector/nodestats_api.go
@@ -63,7 +63,7 @@ type Pipeline struct {
                Failures             int         `json:"failures"`
        } `json:"reloads"`
        Queue struct {
-               Events   int    `json:"events"`
+               Events   int    `json:"events_count"`
                Type     string `json:"type"`
                Capacity struct {
                        QueueSizeInBytes    int   `json:"queue_size_in_bytes"`
```
and build bin

**Comment by sparkblaze** [comment]
That diff failed when I tried to run it...

```
git apply change.diff
error: patch failed: collector/nodestats_api.go:63
error: collector/nodestats_api.go: patch does not apply
```

I manually swapped `"events" to "events_count"`, but the value still seems to sit at 0. I was more interested in the queue size stats which aren't nested under `capacity` anymore. I tried moving them up to under `Queue struct {` but that doesn't seem to have changed anything when I rebuilt it...

**Comment by matejzero** [comment]
I made a fork for LS 7.6 at https://github.com/matejzero/logstash_exporter. It exposes events_count and queue sizes from the new API.

**Comment by mpucholblasco** [comment]
Hi @sparkblaze , @romarioschneider and @matejzero !

My apologies, but these COVID-19 days are being really crazy.

Changing `events` to `events_count` brakes compatibility with older Logstash versions, maybe we should start to analyze which is the Logstash version and decide then.

Proposals (ideas or PRs) are more than welcome!

I will try to do these changes during the weekend.

**Comment by matejzero** [comment]
No problem, we are all in the same bucket regarding COVID.

I'm trying to find the version of Logstash that changed the format, but so far, all I can find out is that this change was introduces between 6.8 and 7.6. I'll do some more testing to try and narrow down the exact version. I checked Logstash changelogs but didn't find anything there. Will report back.

**Comment by matejzero** [comment]
The change was introduced in Logstash version 7.3.0, probably in [PR #10576](https://github.com/elastic/logstash/pull/10576). 

Before 7.3.0:
```json
curl -q -XGET 'localhost:9600/_node/stats/pipelines?pretty' | jq .pipelines.main.queue
{
  "events": 0,
  "capacity": {
    "page_capacity_in_bytes": 67108864,
    "max_queue_size_in_bytes": 1073741824,
    "max_unread_events": 0,
    "queue_size_in_bytes": 1
  },
  "type": "persisted",
  "data": {
    "storage_type": "overlay",
    "path": "/usr/share/logstash/data/queue/main",
    "free_space_in_bytes": 42902822912
  }
}
```

7.3.0 and after:
```json
curl -q -XGET 'localhost:9600/_node/stats/pipelines?pretty' | jq .pipelines.main.queue
{
  "type": "memory",
  "events_count": 0,
  "queue_size_in_bytes": 0,
  "max_queue_size_in_bytes": 0
}
```

I think we should lookup Logstash version and parse the output according to the version. We could get logstash version from Monitoring API:

```json
curl -q -XGET 'localhost:9600/_node/stats/pipelines?pretty' | jq .version
"7.2.1"
```

Version is reported from version 5.0.0 onwards, which is when Monitoring API was introduced, so I think it's a safe way to use it and covers most of the cases (unlike using logstash --version, which is path dependant and is different in docker, linux, windows and cannot be used in K8s, since you don't have access to logstash binary).

Can't help with PR though, no knowledge:/ But will happily test it out:)

**Comment by huepf** [comment]
I guess this is also the reason why I don't get PipelineDeadLetterQueueSizeInBytes with logstash 7.6.2?
Thanks for looking into it.

**Comment by matejzero** [comment]
Might be, yea!

I can check if the path changed and where it is now, but not before Tuesday.

**Comment by mpucholblasco** [comment]
Hi!

Thanks a lot @matejzero for your research on this 👏 

I just released two new versions `v7.3.0.0` and `v5.0.0.0`.  As commented on README, I guess it's better to have different versions (and branches) for each minimum logstash supported version. If you consider there is a better option, please tell me.

Version `v7.3.0.0` fixed the problem commented no this issue, leaving `v5.0.0.0` with support until logstash 7.3.0.

On the other hand, @huepf , I had to add `dead_letter_queue.enable: true` to `logstash.yml` in order to see this metric via `curl -q -XGET 'localhost:9600/_node/stats/pipelines?pretty'`, and it's shown properly on `logstash_exporter`. Could you test this and open a new issue if that metric fails?

**Comment by matejzero** [comment]
The README entry can be wrongly understood (I think). 

Maybe something this way: For instance, `logstash-exporter v5.0.0.0` supports Logstash API from 5.0.0 until 7.2.x. After that version, some metrics can be missing or wrong. `logstash_exporter v7.3.0.0` supports Logstash API from 7.3.0 onwards and so on.

It would be better to have a single `logstash_exporter`, but it makes code more cluttered. We would need to extend the Pipeline and other structs to include new and old fields and then use logstash version to decide which metrics to output and which not. Not a coder, so there might be better ways of achieving this:)

Thanks for the fix and new release. It's already in the pipeline.

**Comment by huepf** [comment]
> On the other hand, @huepf , I had to add `dead_letter_queue.enable: true` to `logstash.yml` in order to see this metric via `curl -q -XGET 'localhost:9600/_node/stats/pipelines?pretty'`, and it's shown properly on `logstash_exporter`. Could you test this and open a new issue if that metric fails?

Also I can confirm that the dead letter queue size metric works. Thanks!

**Comment by roflmao** [comment]
@matejzero I still cant get logstash_node_queue_events for other than {pipeline=".monitoring-logstash"} on my logstash 7.6.2 even though i see it exposed from logstash:9600. The pipeline .monitoring-logstash block has queue: null from logstash.

```
± curl -s 'http://10.244.62.40:9198/metrics' | grep node_queue_events
# HELP logstash_node_queue_events queue_events
# TYPE logstash_node_queue_events counter
logstash_node_queue_events{pipeline=".monitoring-logstash"} 0
```

```
$ curl -s 'http://10.244.62.40:9600/_node/stats/pipelines?pretty' | jq .pipelines.\".monitoring-logstash\".queue
null
$ curl -s 'http://10.244.62.40:9600/_node/stats/pipelines?pretty' | jq .pipelines.main.queue
{
  "type": "memory",
  "events_count": 0,
  "queue_size_in_bytes": 0,
  "max_queue_size_in_bytes": 0
}
```

Running:
```
time="2020-05-27T12:23:55Z" level=info msg="Starting Logstash exporter (version=0.1.5, branch=master, revision=8e1d5cc78afeacbe1085670b0a4f7e14f76193e2)" source="logstash_exporter.go:123"
```

**Comment by mpucholblasco** [comment]
@roflmao , could you test it with version `v7.3.0.0`?

**Comment by roflmao** [comment]
Still no go with ```sequra/logstash_exporter:7.3.0.0```
```
time="2020-05-28T08:18:55Z" level=info msg="Starting Logstash exporter (version=7.3.0.0, branch=master, revision=d522e1c72935fcfcb778de9cb1e2c3718a6ae50f)" source="logstash_exporter.go:123"
```

curls:
```
$ curl -s 'http://10.244.62.41:9198/metrics' | grep node_queue_events
# HELP logstash_node_queue_events queue_events
# TYPE logstash_node_queue_events counter
logstash_node_queue_events{pipeline=".monitoring-logstash"} 0
$ curl -s 'http://10.244.62.41:9600/_node/stats/pipelines?pretty' | jq .pipelines.main.queue
{
  "type": "memory",
  "events_count": 0,
  "queue_size_in_bytes": 0,
  "max_queue_size_in_bytes": 0
}
```

**Comment by mpucholblasco** [comment]
@roflmao , could you add your logstash configuration? I will try to reproduce locally generating random data. Thanks!

**Comment by roflmao** [comment]
@mpucholblasco Im running logstash in kubernetes with image: ```docker.elastic.co/logstash/logstash:7.6.2```:

```
Containers:
  logstash:
    Container ID:   docker://61b4a6a426eba8d2305774798d263c51374033136f71fee0731393839edd31e3
    Image:          docker.elastic.co/logstash/logstash:7.6.2
    Image ID:       docker-pullable://docker.elastic.co/logstash/logstash@sha256:baed5f5bf04299994ea41881afb4d4985cb0f33427a2aef39223c75975bab60e
    Ports:          9600/TCP, 5045/TCP, 5044/TCP, 6515/TCP, 6516/TCP, 6514/UDP, 8080/TCP, 5153/TCP, 5154/TCP, 5170/TCP, 5171/TCP, 5157/UDP
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/UDP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/UDP
    State:          Running
      Started:      Thu, 28 May 2020 10:25:21 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     16
      memory:  12Gi
    Requests:
      cpu:      8
      memory:   5Gi
    Liveness:   http-get http://:monitor/ delay=90s timeout=30s period=30s #success=1 #failure=6
    Readiness:  http-get http://:monitor/ delay=90s timeout=30s period=30s #success=1 #failure=6
    Environment:
      ELASTICSEARCH_HOST:  https://logging-ingest.logging.svc.kube.X.us
      ELASTICSEARCH_PORT:  9200
      LS_HEAP_SIZE:        6g
      LS_JAVA_OPTS:        -Xmx6g
```

logstash-exporter:
```
  logstash-exporter:
    Container ID:  docker://8fc7675e87dff655d8c8afa379f92f98f5a6b910468e8a1a84dea8c57f7514f1
    Image:         sequra/logstash_exporter:7.3.0.0
    Image ID:      docker-pullable://sequra/logstash_exporter@sha256:480750eefc6ddc3f199b522dff264036e9ccbd7a1ad6077c662aedd1877c0548
    Port:          9198/TCP
    Host Port:     0/TCP
    Command:
      /bin/sh
      -c
    Args:
      sleep 60; exec /logstash_exporter
        --logstash.endpoint=http://localhost:9600
        --web.listen-address=:9198
```

logstash.yml
```
http.host: "0.0.0.0"
config.reload.automatic: "false"
path.config: /usr/share/logstash/pipeline
path.data: /usr/share/logstash/data
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: X
xpack.monitoring.elasticsearch.hosts: "https://es.logging.svc.kube.X.us:9200"
xpack.monitoring.elasticsearch.ssl.certificate_authority: "/usr/share/logstash/config/certs/ca.crt"
xpack.monitoring.elasticsearch.ssl.verification_mode: certificate
queue.checkpoint.writes: 1024
queue.drain: "true"
queue.max_bytes: 5gb
queue.type: memory
pipeline.batch.size: 512
dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 1024mb
```

Other than that its just using the main pipeline with input/filter/output, not sure if this is relevant to share in regards of this task.

**Comment by mpucholblasco** [comment]
@roflmao , when all source data is zero
```
$ curl -s 'http://10.244.62.41:9600/_node/stats/pipelines?pretty' | jq .pipelines.main.queue
{
  "type": "memory",
  "events_count": 0,
  "queue_size_in_bytes": 0,
  "max_queue_size_in_bytes": 0
}
```
, it's not taken into account by `logstash_exporter`. It need at least one field with data in order to work properly.

If you change the `queue.type` to `persisted`, then source data is
```
$ curl -s -q -XGET 'localhost:9600/_node/stats/pipelines?pretty' | jq .pipelines.main.queue
{
  "type": "persisted",
  "events_count": 0,
  "queue_size_in_bytes": 16087,
  "max_queue_size_in_bytes": 134217728
}
```
and `logstash_exporter` starts to show this data:
```
$ curl -s localhost:9198/metrics | grep node_queue
# HELP logstash_node_queue_events queue_events
# TYPE logstash_node_queue_events counter
logstash_node_queue_events{pipeline="main"} 0
# HELP logstash_node_queue_max_size_bytes queue_max_size_bytes
# TYPE logstash_node_queue_max_size_bytes counter
logstash_node_queue_max_size_bytes{pipeline="main"} 1.34217728e+08
# HELP logstash_node_queue_size_bytes queue_size_bytes
# TYPE logstash_node_queue_size_bytes counter
logstash_node_queue_size_bytes{pipeline="main"} 16087
```

**Comment by roflmao** [comment]
@mpucholblasco Sorry about the late response, but changing to persistent gives the stats back. Thanks!
